--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1 (Ubuntu 15.1-1.pgdg20.04+1)
-- Dumped by pg_dump version 16.8 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: decrement_news_comments(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.decrement_news_comments() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- Set the role to allow the update
    PERFORM set_config('my.role', 'like_count_func_role', true);
    
    UPDATE news
    SET comments_count = comments_count - 1
    WHERE id = OLD.news_id;
    
    RETURN OLD;
END;
$$;


--
-- Name: decrement_news_likes(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.decrement_news_likes() RETURNS trigger
    LANGUAGE plpgsql
    AS $$BEGIN
    -- Set the role to allow the update
    PERFORM set_config('my.role', 'like_count_func_role', true);
    
    UPDATE news
    SET likes_count = likes_count - 1
    WHERE id = OLD.news_id;
    
    RETURN OLD;
END;$$;


--
-- Name: increment_news_comments(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.increment_news_comments() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$BEGIN
    -- Set the role to allow the update
    PERFORM set_config('my.role', 'like_count_func_role', true);
    
    UPDATE news
    SET comments_count = comments_count + 1
    WHERE id = NEW.news_id;
    
    RETURN NEW;
END;$$;


--
-- Name: increment_news_likes(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.increment_news_likes() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
BEGIN
    -- Set the role to allow the update
    PERFORM set_config('my.role', 'like_count_func_role', true);
    
    UPDATE news
    SET likes_count = likes_count + 1
    WHERE id = NEW.news_id;
    RETURN NEW;
END;
$$;


--
-- Name: insert_public_user_data(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.insert_public_user_data() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
BEGIN
    INSERT INTO public.public_user_data (user_id, avatar_url, display_name)
    VALUES (NEW.id, NULL, NULL);
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: comment_likes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comment_likes (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL,
    comment_id bigint NOT NULL
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    news_id text NOT NULL,
    user_id uuid NOT NULL,
    parent_id bigint,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted boolean DEFAULT false NOT NULL
);


--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.comments_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: comments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.comments_id_seq OWNED BY public.comments.id;


--
-- Name: comments_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exchangeLiqMapCache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."exchangeLiqMapCache" (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    data json NOT NULL,
    asset character varying NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: news; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.news (
    id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    original_url text,
    likes_count bigint DEFAULT '0'::bigint NOT NULL,
    source text,
    comments_count bigint DEFAULT '0'::bigint NOT NULL,
    image_url text,
    sentiment text,
    summary text,
    symbols text[],
    title text,
    published_at timestamp with time zone,
    CONSTRAINT news_comments_count_check CHECK ((comments_count >= 0)),
    CONSTRAINT news_likes_check CHECK ((likes_count >= 0))
);


--
-- Name: news_bookmarks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.news_bookmarks (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    news_id text NOT NULL,
    user_id uuid DEFAULT auth.uid() NOT NULL,
    CONSTRAINT news_bookmarks_user_id_check CHECK ((user_id = auth.uid()))
);


--
-- Name: news_bookmarks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.news_bookmarks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_bookmarks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_likes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.news_likes (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    news_id text NOT NULL,
    user_id uuid DEFAULT auth.uid() NOT NULL,
    CONSTRAINT news_likes_user_id_check CHECK ((user_id = auth.uid()))
);


--
-- Name: news_likes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.news_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: public_user_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.public_user_data (
    user_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    display_name text,
    avatar_url text
);


--
-- Name: sentiment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sentiment (
    id bigint NOT NULL,
    sentiment smallint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    device_id text DEFAULT gen_random_uuid() NOT NULL
);


--
-- Name: sentiment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sentiment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sentiment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: smart_signals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.smart_signals (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id bigint NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    topics text[] NOT NULL,
    condition text NOT NULL,
    fired_at timestamp with time zone,
    actions jsonb[]
);


--
-- Name: smart_signals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.smart_signals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.smart_signals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscriptions (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    price_id text,
    subscription_id text NOT NULL,
    user_id uuid,
    updated_at timestamp with time zone,
    start_timestamp timestamp with time zone,
    end_timestamp timestamp with time zone,
    has_cancelled boolean DEFAULT false NOT NULL,
    plan_name text
);


--
-- Name: TABLE subscriptions; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.subscriptions IS 'User subscriptions record';


--
-- Name: subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    username text,
    email text,
    updated_at timestamp with time zone,
    user_id uuid NOT NULL,
    has_had_free_trial boolean DEFAULT false NOT NULL
);


--
-- Name: TABLE users; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.users IS 'Users Table';


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);


--
-- Name: comment_likes comment_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT comment_likes_pkey PRIMARY KEY (user_id, comment_id);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: exchangeLiqMapCache exchangeLiqMapCache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."exchangeLiqMapCache"
    ADD CONSTRAINT "exchangeLiqMapCache_pkey" PRIMARY KEY (asset);


--
-- Name: news_bookmarks news_bookmarks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_bookmarks
    ADD CONSTRAINT news_bookmarks_pkey PRIMARY KEY (id);


--
-- Name: news news_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_id_key UNIQUE (id);


--
-- Name: news_likes news_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_likes
    ADD CONSTRAINT news_likes_pkey PRIMARY KEY (id);


--
-- Name: news news_original_url_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_original_url_key UNIQUE (original_url);


--
-- Name: public_user_data public_user_data_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_user_data
    ADD CONSTRAINT public_user_data_pkey PRIMARY KEY (user_id);


--
-- Name: sentiment sentiment_device_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sentiment
    ADD CONSTRAINT sentiment_device_id_key UNIQUE (device_id);


--
-- Name: sentiment sentiment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sentiment
    ADD CONSTRAINT sentiment_pkey PRIMARY KEY (id);


--
-- Name: smart_signals smart_signals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.smart_signals
    ADD CONSTRAINT smart_signals_pkey PRIMARY KEY (id);


--
-- Name: subscriptions subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);


--
-- Name: subscriptions subscriptions_subscription_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_subscription_id_key UNIQUE (subscription_id);


--
-- Name: news_bookmarks unique_bookmarks; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_bookmarks
    ADD CONSTRAINT unique_bookmarks UNIQUE (news_id, user_id);


--
-- Name: news_likes unique_news_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_likes
    ADD CONSTRAINT unique_news_user UNIQUE (news_id, user_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_id_key UNIQUE (user_id);


--
-- Name: unique_lower_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unique_lower_email ON public.users USING btree (lower(email));


--
-- Name: exchangeLiqMapCache handle_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public."exchangeLiqMapCache" FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


--
-- Name: comments on_news_comments_delete; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_news_comments_delete BEFORE DELETE ON public.comments FOR EACH ROW EXECUTE FUNCTION public.decrement_news_comments();


--
-- Name: comments on_news_comments_insert; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_news_comments_insert BEFORE INSERT ON public.comments FOR EACH ROW EXECUTE FUNCTION public.increment_news_comments();


--
-- Name: news_likes on_news_likes_delete; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_news_likes_delete BEFORE DELETE ON public.news_likes FOR EACH ROW EXECUTE FUNCTION public.decrement_news_likes();


--
-- Name: news_likes on_news_likes_insert; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_news_likes_insert BEFORE INSERT ON public.news_likes FOR EACH ROW EXECUTE FUNCTION public.increment_news_likes();


--
-- Name: comment_likes comment_likes_comment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT comment_likes_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.comments(id);


--
-- Name: comment_likes comment_likes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT comment_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


--
-- Name: comments comments_news_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_news_id_fkey FOREIGN KEY (news_id) REFERENCES public.news(id) ON DELETE CASCADE;


--
-- Name: comments comments_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.comments(id) ON DELETE RESTRICT;


--
-- Name: comments comments_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


--
-- Name: comments comments_user_id_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_user_id_fkey1 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: comments comments_user_id_fkey2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_user_id_fkey2 FOREIGN KEY (user_id) REFERENCES public.public_user_data(user_id);


--
-- Name: news_bookmarks news_bookmarks_news_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_bookmarks
    ADD CONSTRAINT news_bookmarks_news_id_fkey FOREIGN KEY (news_id) REFERENCES public.news(id) ON DELETE CASCADE;


--
-- Name: news_bookmarks news_bookmarks_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_bookmarks
    ADD CONSTRAINT news_bookmarks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: news_bookmarks news_bookmarks_user_id_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_bookmarks
    ADD CONSTRAINT news_bookmarks_user_id_fkey1 FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: news_likes news_likes_news_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_likes
    ADD CONSTRAINT news_likes_news_id_fkey FOREIGN KEY (news_id) REFERENCES public.news(id) ON DELETE CASCADE;


--
-- Name: news_likes news_likes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_likes
    ADD CONSTRAINT news_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: news_likes news_likes_user_id_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_likes
    ADD CONSTRAINT news_likes_user_id_fkey1 FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: public_user_data public_user_data_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_user_data
    ADD CONSTRAINT public_user_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


--
-- Name: smart_signals smart_signals_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.smart_signals
    ADD CONSTRAINT smart_signals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: comment_likes Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable delete for users based on user_id" ON public.comment_likes FOR DELETE USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: news_bookmarks Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable delete for users based on user_id" ON public.news_bookmarks FOR DELETE USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: news_likes Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable delete for users based on user_id" ON public.news_likes FOR DELETE USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: comment_likes Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for authenticated users only" ON public.comment_likes FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: news_bookmarks Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for authenticated users only" ON public.news_bookmarks FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: news_likes Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for authenticated users only" ON public.news_likes FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: public_user_data Enable insert for users based on user_id; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for users based on user_id" ON public.public_user_data FOR INSERT WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: news Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.news FOR SELECT USING (true);


--
-- Name: public_user_data Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.public_user_data FOR SELECT USING (true);


--
-- Name: public_user_data Enable update for users based on user_id; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable update for users based on user_id" ON public.public_user_data FOR UPDATE USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: comment_likes Enable users to view their own data only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable users to view their own data only" ON public.comment_likes FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: news_bookmarks Enable users to view their own data only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable users to view their own data only" ON public.news_bookmarks FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: news_likes Enable users to view their own data only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable users to view their own data only" ON public.news_likes FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: subscriptions Only Auth User; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Only Auth User" ON public.subscriptions USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));


--
-- Name: users Only Auth User; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Only Auth User" ON public.users USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));


--
-- Name: sentiment Only Service Role; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Only Service Role" ON public.sentiment TO service_role USING (true) WITH CHECK (true);


--
-- Name: comments Users can delete their own comments; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can delete their own comments" ON public.comments FOR DELETE USING ((auth.uid() = user_id));


--
-- Name: comments Users can insert their own comments; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can insert their own comments" ON public.comments FOR INSERT WITH CHECK ((auth.uid() = user_id));


--
-- Name: comments Users can read all comments; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can read all comments" ON public.comments FOR SELECT USING (true);


--
-- Name: comments Users can update their own comments; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can update their own comments" ON public.comments FOR UPDATE USING ((auth.uid() = user_id));


--
-- Name: comment_likes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.comment_likes ENABLE ROW LEVEL SECURITY;

--
-- Name: comments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

--
-- Name: exchangeLiqMapCache; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public."exchangeLiqMapCache" ENABLE ROW LEVEL SECURITY;

--
-- Name: news like_count_func_role can update news; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "like_count_func_role can update news" ON public.news FOR UPDATE TO authenticated USING ((current_setting('my.role'::text) = 'like_count_func_role'::text)) WITH CHECK ((current_setting('my.role'::text) = 'like_count_func_role'::text));


--
-- Name: news; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

--
-- Name: news_bookmarks; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.news_bookmarks ENABLE ROW LEVEL SECURITY;

--
-- Name: news_likes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.news_likes ENABLE ROW LEVEL SECURITY;

--
-- Name: public_user_data; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.public_user_data ENABLE ROW LEVEL SECURITY;

--
-- Name: sentiment; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.sentiment ENABLE ROW LEVEL SECURITY;

--
-- Name: smart_signals; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.smart_signals ENABLE ROW LEVEL SECURITY;

--
-- Name: subscriptions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

--
-- Name: users; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

