export const tokenArray = [
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/BTC.png",
    symbol: "BTC",
    name: "Bitcoin",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/ETH.png",
    symbol: "ETH",
    name: "Ethereum",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/BNB.png",
    symbol: "BNB",
    name: "BNB",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/XRP.png",
    symbol: "XRP",
    name: "XRP",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/SOL.png",
    symbol: "SOL",
    name: "Solana",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/ADA.png",
    symbol: "ADA",
    name: "Cardano",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/LUNA.png",
    symbol: "LUNA",
    name: "Terra",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/AVAX.png",
    symbol: "AVAX",
    name: "Avalanche",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/DOGE.png",
    symbol: "DOGE",
    name: "Dogecoin",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/DOT.png",
    symbol: "DOT",
    name: "Polkadot",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/SHIB.png",
    symbol: "SHIB",
    name: "Shiba Inu",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/MATIC.png",
    symbol: "MATIC",
    name: "Polygon",
    color: "",
    slug: "",
    is_free: true,
  },

  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/TRX.png",
    symbol: "TRX",
    name: "TRON",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/XLM.png",
    symbol: "XLM",
    name: "Stellar",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/LINK.png",
    symbol: "LINK",
    name: "Chainlink",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/UNI.png",
    symbol: "UNI",
    name: "Uniswap",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/FTM.png",
    symbol: "FTM",
    name: "Fantom",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/ALGO.png",
    symbol: "ALGO",
    name: "Algorand",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/MANA.png",
    symbol: "MANA",
    name: "Decentraland",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/LTC.png",
    symbol: "LTC",
    name: "Litecoin",
    color: "",
    slug: "",
    is_free: true,
  },

  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/FTT.png",
    symbol: "FTT",
    name: "FTX Token",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/NEAR.png",
    symbol: "NEAR",
    name: "NEAR Protocol",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/BCH.png",
    symbol: "BCH",
    name: "Bitcoin Cash",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/ETC.png",
    symbol: "ETC",
    name: "Ethereum Classic",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/XMR.png",
    symbol: "XMR",
    name: "Monero",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/ATOM.png",
    symbol: "ATOM",
    name: "Cosmos",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/VET.png",
    symbol: "VET",
    name: "VeChain",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/HBAR.png",
    symbol: "HBAR",
    name: "Hedera",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/FLOW.png",
    symbol: "FLOW",
    name: "Flow",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/ICP.png",
    symbol: "ICP",
    name: "Internet Computer",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/APE.png",
    symbol: "APE",
    name: "ApeCoin",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/EGLD.png",
    symbol: "EGLD",
    name: "MultiversX (Elrond)",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/XTZ.png",
    symbol: "XTZ",
    name: "Tezos",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/THETA.png",
    symbol: "THETA",
    name: "Theta Network",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/HNT.png",
    symbol: "HNT",
    name: "Helium",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/FIL.png",
    symbol: "FIL",
    name: "Filecoin",
    color: "",
    slug: "",
    is_free: true,
  },

  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/AXS.png",
    symbol: "AXS",
    name: "Axie Infinity",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/SAND.png",
    symbol: "SAND",
    name: "The Sandbox",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/ZEC.png",
    symbol: "ZEC",
    name: "Zcash",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/EOS.png",
    symbol: "EOS",
    name: "EOS",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/IOTA.png",
    symbol: "IOTA",
    name: "IOTA",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/PEPE.png",
    symbol: "PEPE",
    name: "Pepe",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/ARB.png",
    symbol: "ARB",
    name: "Arbitrum",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/INJ.png",
    symbol: "INJ",
    name: "Injective",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/GRT.png",
    symbol: "GRT",
    name: "The Graph",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/WIF.png",
    symbol: "WIF",
    name: "dogwifhat",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/SUI.png",
    symbol: "SUI",
    name: "Sui",
    color: "",
    slug: "",
    is_free: true,
  },

  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/BONK.png",
    symbol: "BONK",
    name: "Bonk",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/NOT.png",
    symbol: "NOT",
    name: "Notcoin",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/AAVE.png",
    symbol: "AAVE",
    name: "Aave",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/JUP.png",
    symbol: "JUP",
    name: "Jupiter",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/SEI.png",
    symbol: "SEI",
    name: "Sei",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/GALA.png",
    symbol: "GALA",
    name: "Gala",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/BTT.png",
    symbol: "BTT",
    name: "BitTorrent",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/TON.png",
    symbol: "TON",
    name: "Toncoin",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/NEIRO.png",
    symbol: "NEIRO",
    name: "Neiro AI",
    color: "",
    slug: "",
    is_free: true,
  },

  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/FET.png",
    symbol: "FET",
    name: "Fetch.ai",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/EIGEN.png",
    symbol: "EIGEN",
    name: "EigenLayer",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/OG.png",
    symbol: "OG",
    name: "OG Fan Token",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/POLY.png",
    symbol: "POLY",
    name: "Polymath",
    color: "",
    slug: "",
    is_free: true,
  },

  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/KAS.png",
    symbol: "KAS",
    name: "Kaspa",
    color: "",
    slug: "",
    is_free: true,
  },

  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/FLOKI.png",
    symbol: "FLOKI",
    name: "Floki",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/RUNE.png",
    symbol: "RUNE",
    name: "THORChain",
    color: "",
    slug: "",
    is_free: true,
  },
  {
    price: 0,
    priceChange: 0,
    marketCap: 0,
    volume: 0,
    icon: "https://bin.bnbstatic.com/static/assets/logos/TRUMP.png",
    symbol: "TRUMP",
    name: "TrumpCoin",
    color: "",
    slug: "",
    is_free: true,
  },
];
