create sequence "public"."milestones_id_seq";

create sequence "public"."payout_audit_log_id_seq";

create sequence "public"."payouts_id_seq";

drop policy "Enable users to view their own data only" on "public"."users";

drop policy "Only Auth User" on "public"."users";

alter table "public"."kol_platforms" drop constraint "fk_kol_id";

alter table "public"."news" drop constraint "news_original_url_key";

alter table "public"."campaigns" drop constraint "campaigns_status_check";

alter table "public"."project_members" drop constraint "project_members_role_check";

alter table "public"."projects" drop constraint "projects_status_check";

alter table "public"."user_roles" drop constraint "user_roles_role_check";

drop view if exists "public"."campaign_with_meta";

drop view if exists "public"."signals_users";

drop index if exists "public"."campaign_platforms_campaign_id_idx";

drop index if exists "public"."campaign_tags_campaign_id_idx";

drop index if exists "public"."campaigns_end_date_idx";

drop index if exists "public"."campaigns_project_id_status_idx";

drop index if exists "public"."campaigns_start_date_idx";

drop index if exists "public"."campaigns_title_idx";

drop index if exists "public"."kol_requests_campaign_id_idx";

drop index if exists "public"."news_original_url_key";

drop index if exists "public"."unq_kol_campaign";

create table "public"."kol_milestones" (
    "campaign_id" integer not null,
    "milestone_id" integer not null,
    "kol_id" integer not null,
    "hits" integer not null default 0
);


create table "public"."milestones" (
    "id" integer not null default nextval('milestones_id_seq'::regclass),
    "campaign_id" integer not null,
    "title" character varying(255) not null,
    "description" text,
    "type" character varying(50) default 'likes'::character varying,
    "quota" integer not null default 0,
    "hits" integer not null default 0,
    "payout_amount" numeric(12,2) not null,
    "payout_id" integer,
    "status" character varying(20) not null default 'active'::character varying,
    "deadline" date,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


create table "public"."news_favorites" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default gen_random_uuid(),
    "news_id" text not null default gen_random_uuid()
);


alter table "public"."news_favorites" enable row level security;

create table "public"."payout_audit_log" (
    "id" integer not null default nextval('payout_audit_log_id_seq'::regclass),
    "payout_id" integer not null,
    "action" character varying(50) not null,
    "old_status" character varying(20),
    "new_status" character varying(20),
    "performed_by" uuid not null,
    "notes" text,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."payouts" (
    "id" integer not null default nextval('payouts_id_seq'::regclass),
    "kol_id" integer not null,
    "milestone_id" integer,
    "campaign_id" integer not null,
    "wallet_address" character varying(512) not null,
    "tx_id" character varying(512),
    "amount" numeric(12,2) not null,
    "chain" character varying(50) not null default 'ethereum'::character varying,
    "status" character varying(20) not null default 'pending'::character varying,
    "approved_by" uuid,
    "approved_at" timestamp with time zone,
    "paid_at" timestamp with time zone,
    "rejection_reason" text,
    "notes" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."campaigns" add column "campaign_brief" character varying(512);

alter table "public"."campaigns" add column "campaign_type" character varying(100);

alter table "public"."campaigns" add column "category" character varying(100);

alter table "public"."campaigns" add column "content_types" text[];

alter table "public"."campaigns" add column "external_links" jsonb default '[]'::jsonb;

alter table "public"."campaigns" add column "faqs" jsonb default '[]'::jsonb;

alter table "public"."campaigns" add column "impressions" bigint default 0;

alter table "public"."campaigns" add column "location" character varying(255);

alter table "public"."campaigns" add column "media_kit" character varying(512);

alter table "public"."campaigns" add column "milestones" jsonb default '[]'::jsonb;

alter table "public"."campaigns" add column "platforms" text[];

alter table "public"."campaigns" add column "reference_content" character varying(512);

alter table "public"."campaigns" add column "requirements" jsonb default '[]'::jsonb;

alter table "public"."campaigns" add column "resources" jsonb default '[]'::jsonb;

alter table "public"."campaigns" add column "reward_type" character varying(50) default 'fixed'::character varying;

alter table "public"."campaigns" add column "tags" text[];

alter table "public"."campaigns" add column "terms_and_conditions" text;

alter table "public"."campaigns" add column "total_spend" numeric(12,2) default 0;

alter table "public"."campaigns" add column "total_spots" integer;

alter table "public"."kols" alter column "onboarding" drop not null;

alter table "public"."users" add column "avatar_url" text;

alter sequence "public"."milestones_id_seq" owned by "public"."milestones"."id";

alter sequence "public"."payout_audit_log_id_seq" owned by "public"."payout_audit_log"."id";

alter sequence "public"."payouts_id_seq" owned by "public"."payouts"."id";

CREATE INDEX idx_campaign_platforms_campaign_id ON public.campaign_platforms USING btree (campaign_id);

CREATE INDEX idx_campaign_tags_campaign_id ON public.campaign_tags USING btree (campaign_id);

CREATE INDEX idx_campaigns_campaign_type ON public.campaigns USING btree (campaign_type);

CREATE INDEX idx_campaigns_category ON public.campaigns USING btree (category);

CREATE INDEX idx_campaigns_content_types ON public.campaigns USING gin (content_types);

CREATE INDEX idx_campaigns_end_date ON public.campaigns USING btree (end_date);

CREATE INDEX idx_campaigns_external_links ON public.campaigns USING gin (external_links);

CREATE INDEX idx_campaigns_faqs ON public.campaigns USING gin (faqs);

CREATE INDEX idx_campaigns_location ON public.campaigns USING btree (location);

CREATE INDEX idx_campaigns_milestones ON public.campaigns USING gin (milestones);

CREATE INDEX idx_campaigns_platforms ON public.campaigns USING gin (platforms);

CREATE INDEX idx_campaigns_project_id ON public.campaigns USING btree (project_id, status);

CREATE INDEX idx_campaigns_requirements ON public.campaigns USING gin (requirements);

CREATE INDEX idx_campaigns_reward_type ON public.campaigns USING btree (reward_type);

CREATE INDEX idx_campaigns_start_date ON public.campaigns USING btree (start_date);

CREATE INDEX idx_campaigns_tags ON public.campaigns USING gin (tags);

CREATE INDEX idx_campaigns_title ON public.campaigns USING gin (title gin_trgm_ops);

CREATE INDEX idx_kol_requests_campaign_id ON public.kol_requests USING btree (campaign_id);

CREATE INDEX idx_milestones_campaign_id ON public.milestones USING btree (campaign_id);

CREATE INDEX idx_milestones_deadline ON public.milestones USING btree (deadline);

CREATE INDEX idx_milestones_hits_quota ON public.milestones USING btree (hits, quota);

CREATE INDEX idx_milestones_status ON public.milestones USING btree (status);

CREATE INDEX idx_milestones_type ON public.milestones USING btree (type);

CREATE INDEX idx_payout_audit_log_created_at ON public.payout_audit_log USING btree (created_at);

CREATE INDEX idx_payout_audit_log_payout_id ON public.payout_audit_log USING btree (payout_id);

CREATE INDEX idx_payout_audit_log_performed_by ON public.payout_audit_log USING btree (performed_by);

CREATE INDEX idx_payouts_approved_by ON public.payouts USING btree (approved_by);

CREATE INDEX idx_payouts_campaign_id ON public.payouts USING btree (campaign_id);

CREATE INDEX idx_payouts_created_at ON public.payouts USING btree (created_at);

CREATE INDEX idx_payouts_kol_id ON public.payouts USING btree (kol_id);

CREATE INDEX idx_payouts_milestone_id ON public.payouts USING btree (milestone_id);

CREATE INDEX idx_payouts_status ON public.payouts USING btree (status);

CREATE UNIQUE INDEX milestones_pkey ON public.milestones USING btree (id);

CREATE UNIQUE INDEX news_favorites_pkey ON public.news_favorites USING btree (id);

CREATE UNIQUE INDEX payout_audit_log_pkey ON public.payout_audit_log USING btree (id);

CREATE UNIQUE INDEX payouts_pkey ON public.payouts USING btree (id);

CREATE UNIQUE INDEX unq_kol_milestones_campaign ON public.kol_milestones USING btree (kol_id, campaign_id);

CREATE UNIQUE INDEX unq_kol_requests_campaign ON public.kol_requests USING btree (kol_id, campaign_id);

alter table "public"."milestones" add constraint "milestones_pkey" PRIMARY KEY using index "milestones_pkey";

alter table "public"."news_favorites" add constraint "news_favorites_pkey" PRIMARY KEY using index "news_favorites_pkey";

alter table "public"."payout_audit_log" add constraint "payout_audit_log_pkey" PRIMARY KEY using index "payout_audit_log_pkey";

alter table "public"."payouts" add constraint "payouts_pkey" PRIMARY KEY using index "payouts_pkey";

alter table "public"."kol_milestones" add constraint "kol_milestones_campaign_id_fkey" FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE not valid;

alter table "public"."kol_milestones" validate constraint "kol_milestones_campaign_id_fkey";

alter table "public"."kol_milestones" add constraint "kol_milestones_kol_id_fkey" FOREIGN KEY (kol_id) REFERENCES kols(id) ON DELETE CASCADE not valid;

alter table "public"."kol_milestones" validate constraint "kol_milestones_kol_id_fkey";

alter table "public"."kol_milestones" add constraint "kol_milestones_milestone_id_fkey" FOREIGN KEY (milestone_id) REFERENCES milestones(id) ON DELETE CASCADE not valid;

alter table "public"."kol_milestones" validate constraint "kol_milestones_milestone_id_fkey";

alter table "public"."milestones" add constraint "milestones_campaign_id_fkey" FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE not valid;

alter table "public"."milestones" validate constraint "milestones_campaign_id_fkey";

alter table "public"."milestones" add constraint "milestones_payout_id_fkey" FOREIGN KEY (payout_id) REFERENCES payouts(id) not valid;

alter table "public"."milestones" validate constraint "milestones_payout_id_fkey";

alter table "public"."milestones" add constraint "milestones_status_check" CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'paused'::character varying, 'completed'::character varying, 'cancelled'::character varying])::text[]))) not valid;

alter table "public"."milestones" validate constraint "milestones_status_check";

alter table "public"."milestones" add constraint "milestones_type_check" CHECK (((type)::text = ANY ((ARRAY['likes'::character varying, 'shares'::character varying, 'impressions'::character varying, 'comments'::character varying])::text[]))) not valid;

alter table "public"."milestones" validate constraint "milestones_type_check";

alter table "public"."news_favorites" add constraint "news_favorites_news_id_fkey" FOREIGN KEY (news_id) REFERENCES news(id) not valid;

alter table "public"."news_favorites" validate constraint "news_favorites_news_id_fkey";

alter table "public"."news_favorites" add constraint "news_favorites_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(user_id) not valid;

alter table "public"."news_favorites" validate constraint "news_favorites_user_id_fkey";

alter table "public"."payout_audit_log" add constraint "payout_audit_log_payout_id_fkey" FOREIGN KEY (payout_id) REFERENCES payouts(id) ON DELETE CASCADE not valid;

alter table "public"."payout_audit_log" validate constraint "payout_audit_log_payout_id_fkey";

alter table "public"."payout_audit_log" add constraint "payout_audit_log_performed_by_fkey" FOREIGN KEY (performed_by) REFERENCES users(user_id) not valid;

alter table "public"."payout_audit_log" validate constraint "payout_audit_log_performed_by_fkey";

alter table "public"."payouts" add constraint "fk_payouts_milestone" FOREIGN KEY (milestone_id) REFERENCES milestones(id) ON DELETE SET NULL not valid;

alter table "public"."payouts" validate constraint "fk_payouts_milestone";

alter table "public"."payouts" add constraint "payouts_approved_by_fkey" FOREIGN KEY (approved_by) REFERENCES users(user_id) not valid;

alter table "public"."payouts" validate constraint "payouts_approved_by_fkey";

alter table "public"."payouts" add constraint "payouts_campaign_id_fkey" FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE not valid;

alter table "public"."payouts" validate constraint "payouts_campaign_id_fkey";

alter table "public"."payouts" add constraint "payouts_kol_id_fkey" FOREIGN KEY (kol_id) REFERENCES kols(id) ON DELETE CASCADE not valid;

alter table "public"."payouts" validate constraint "payouts_kol_id_fkey";

alter table "public"."payouts" add constraint "payouts_status_check" CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'paid'::character varying])::text[]))) not valid;

alter table "public"."payouts" validate constraint "payouts_status_check";

alter table "public"."campaigns" add constraint "campaigns_status_check" CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'active'::character varying, 'paused'::character varying, 'completed'::character varying, 'cancelled'::character varying])::text[]))) not valid;

alter table "public"."campaigns" validate constraint "campaigns_status_check";

alter table "public"."project_members" add constraint "project_members_role_check" CHECK (((role)::text = ANY ((ARRAY['owner'::character varying, 'manager'::character varying])::text[]))) not valid;

alter table "public"."project_members" validate constraint "project_members_role_check";

alter table "public"."projects" add constraint "projects_status_check" CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'active'::character varying, 'completed'::character varying, 'archived'::character varying])::text[]))) not valid;

alter table "public"."projects" validate constraint "projects_status_check";

alter table "public"."user_roles" add constraint "user_roles_role_check" CHECK (((role)::text = ANY ((ARRAY['admin'::character varying, 'manager'::character varying])::text[]))) not valid;

alter table "public"."user_roles" validate constraint "user_roles_role_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_payout_request_on_milestone_completion()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Check if milestone just reached quota and doesn't have a payout yet
    IF NEW.hits >= NEW.quota AND OLD.hits < OLD.quota AND NEW.payout_id IS NULL THEN
        -- Create payout request
        INSERT INTO payouts (
            kol_id, 
            milestone_id, 
            campaign_id, 
            wallet_address, 
            amount, 
            status
        )
        SELECT 
            NEW.kol_id,
            NEW.id,
            NEW.campaign_id,
            k.wallet_address,
            NEW.payout_amount,
            'pending'
        FROM kols k
        WHERE k.id = NEW.kol_id;
    END IF;
    
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.log_payout_status_change()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF TG_OP = 'UPDATE' AND OLD.status != NEW.status THEN
        INSERT INTO payout_audit_log (
            payout_id,
            action,
            old_status,
            new_status,
            performed_by,
            notes
        ) VALUES (
            NEW.id,
            CASE 
                WHEN NEW.status = 'approved' THEN 'approved'
                WHEN NEW.status = 'rejected' THEN 'rejected'
                WHEN NEW.status = 'paid' THEN 'paid'
                ELSE 'updated'
            END,
            OLD.status,
            NEW.status,
            NEW.approved_by,
            NEW.notes
        );
    END IF;
    
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_user_avatar_from_auth()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  auth_avatar_url TEXT;
BEGIN
  -- Check if the new user's ID exists in auth.users
  SELECT raw_user_meta_data ->> 'avatar_url'
  INTO auth_avatar_url
  FROM auth.users
  WHERE id = NEW.id; -- NEW refers to the row just inserted into public.users

  -- If an avatar URL is found in auth.users, set it for the new user
  IF auth_avatar_url IS NOT NULL THEN
    NEW.avatar_url = auth_avatar_url;
  END IF;

  RETURN NEW; -- Return the modified new row
END;
$function$
;

create or replace view "public"."campaign_with_meta" as  SELECT c.id,
    c.project_id,
    c.title,
    c.description,
    c.banner_url,
    c.status,
    c.start_date,
    c.end_date,
    c.budget,
    c.target_audience,
    c.reward_type,
    c.campaign_type,
    c.category,
    c.total_spots,
    c.location,
    c.terms_and_conditions,
    c.campaign_brief,
    c.reference_content,
    c.media_kit,
    c.milestones,
    c.requirements,
    c.external_links,
    c.faqs,
    c.content_types,
    c.platforms,
    c.tags,
    c.created_at,
    c.updated_at,
    c.total_spend,
    c.impressions,
    COALESCE(array_agg(DISTINCT t.name) FILTER (WHERE (t.name IS NOT NULL)), '{}'::character varying[]) AS tag_list,
    COALESCE(array_agg(DISTINCT cp.platform) FILTER (WHERE (cp.platform IS NOT NULL)), '{}'::character varying[]) AS platform_list,
    max(kr.payment_amount) AS max_payout,
    count(kr.*) AS request_count,
    count(DISTINCT m.id) AS milestone_count,
    count(DISTINCT m.id) FILTER (WHERE ((m.status)::text = 'active'::text)) AS active_milestones,
    count(DISTINCT m.id) FILTER (WHERE ((m.hits >= m.quota) AND (m.payout_id IS NULL))) AS pending_payouts,
    count(DISTINCT m.id) FILTER (WHERE (((m.status)::text = 'completed'::text) OR (m.payout_id IS NOT NULL))) AS completed_milestones,
    count(DISTINCT pay.id) AS total_payouts,
    count(DISTINCT pay.id) FILTER (WHERE ((pay.status)::text = 'paid'::text)) AS paid_payouts,
    COALESCE(sum(pay.amount) FILTER (WHERE ((pay.status)::text = 'paid'::text)), (0)::numeric) AS total_paid_amount,
    COALESCE(sum(pay.amount) FILTER (WHERE ((pay.status)::text = 'pending'::text)), (0)::numeric) AS pending_payout_amount
   FROM ((((((campaigns c
     LEFT JOIN campaign_tags ct ON ((ct.campaign_id = c.id)))
     LEFT JOIN tags t ON ((t.id = ct.tag_id)))
     LEFT JOIN campaign_platforms cp ON ((cp.campaign_id = c.id)))
     LEFT JOIN kol_requests kr ON ((kr.campaign_id = c.id)))
     LEFT JOIN milestones m ON ((m.campaign_id = c.id)))
     LEFT JOIN payouts pay ON ((pay.campaign_id = c.id)))
  GROUP BY c.id;


create or replace view "public"."signals_users" as  SELECT users.user_id,
    users.username,
    smart_signals.id,
    smart_signals.fired_at,
    smart_signals.topics,
    smart_signals.condition
   FROM (smart_signals
     JOIN users ON ((smart_signals.user_id = users.id)));


grant delete on table "public"."kol_milestones" to "anon";

grant insert on table "public"."kol_milestones" to "anon";

grant references on table "public"."kol_milestones" to "anon";

grant select on table "public"."kol_milestones" to "anon";

grant trigger on table "public"."kol_milestones" to "anon";

grant truncate on table "public"."kol_milestones" to "anon";

grant update on table "public"."kol_milestones" to "anon";

grant delete on table "public"."kol_milestones" to "authenticated";

grant insert on table "public"."kol_milestones" to "authenticated";

grant references on table "public"."kol_milestones" to "authenticated";

grant select on table "public"."kol_milestones" to "authenticated";

grant trigger on table "public"."kol_milestones" to "authenticated";

grant truncate on table "public"."kol_milestones" to "authenticated";

grant update on table "public"."kol_milestones" to "authenticated";

grant delete on table "public"."kol_milestones" to "service_role";

grant insert on table "public"."kol_milestones" to "service_role";

grant references on table "public"."kol_milestones" to "service_role";

grant select on table "public"."kol_milestones" to "service_role";

grant trigger on table "public"."kol_milestones" to "service_role";

grant truncate on table "public"."kol_milestones" to "service_role";

grant update on table "public"."kol_milestones" to "service_role";

grant delete on table "public"."milestones" to "anon";

grant insert on table "public"."milestones" to "anon";

grant references on table "public"."milestones" to "anon";

grant select on table "public"."milestones" to "anon";

grant trigger on table "public"."milestones" to "anon";

grant truncate on table "public"."milestones" to "anon";

grant update on table "public"."milestones" to "anon";

grant delete on table "public"."milestones" to "authenticated";

grant insert on table "public"."milestones" to "authenticated";

grant references on table "public"."milestones" to "authenticated";

grant select on table "public"."milestones" to "authenticated";

grant trigger on table "public"."milestones" to "authenticated";

grant truncate on table "public"."milestones" to "authenticated";

grant update on table "public"."milestones" to "authenticated";

grant delete on table "public"."milestones" to "service_role";

grant insert on table "public"."milestones" to "service_role";

grant references on table "public"."milestones" to "service_role";

grant select on table "public"."milestones" to "service_role";

grant trigger on table "public"."milestones" to "service_role";

grant truncate on table "public"."milestones" to "service_role";

grant update on table "public"."milestones" to "service_role";

grant delete on table "public"."news_favorites" to "anon";

grant insert on table "public"."news_favorites" to "anon";

grant references on table "public"."news_favorites" to "anon";

grant select on table "public"."news_favorites" to "anon";

grant trigger on table "public"."news_favorites" to "anon";

grant truncate on table "public"."news_favorites" to "anon";

grant update on table "public"."news_favorites" to "anon";

grant delete on table "public"."news_favorites" to "authenticated";

grant insert on table "public"."news_favorites" to "authenticated";

grant references on table "public"."news_favorites" to "authenticated";

grant select on table "public"."news_favorites" to "authenticated";

grant trigger on table "public"."news_favorites" to "authenticated";

grant truncate on table "public"."news_favorites" to "authenticated";

grant update on table "public"."news_favorites" to "authenticated";

grant delete on table "public"."news_favorites" to "service_role";

grant insert on table "public"."news_favorites" to "service_role";

grant references on table "public"."news_favorites" to "service_role";

grant select on table "public"."news_favorites" to "service_role";

grant trigger on table "public"."news_favorites" to "service_role";

grant truncate on table "public"."news_favorites" to "service_role";

grant update on table "public"."news_favorites" to "service_role";

grant delete on table "public"."payout_audit_log" to "anon";

grant insert on table "public"."payout_audit_log" to "anon";

grant references on table "public"."payout_audit_log" to "anon";

grant select on table "public"."payout_audit_log" to "anon";

grant trigger on table "public"."payout_audit_log" to "anon";

grant truncate on table "public"."payout_audit_log" to "anon";

grant update on table "public"."payout_audit_log" to "anon";

grant delete on table "public"."payout_audit_log" to "authenticated";

grant insert on table "public"."payout_audit_log" to "authenticated";

grant references on table "public"."payout_audit_log" to "authenticated";

grant select on table "public"."payout_audit_log" to "authenticated";

grant trigger on table "public"."payout_audit_log" to "authenticated";

grant truncate on table "public"."payout_audit_log" to "authenticated";

grant update on table "public"."payout_audit_log" to "authenticated";

grant delete on table "public"."payout_audit_log" to "service_role";

grant insert on table "public"."payout_audit_log" to "service_role";

grant references on table "public"."payout_audit_log" to "service_role";

grant select on table "public"."payout_audit_log" to "service_role";

grant trigger on table "public"."payout_audit_log" to "service_role";

grant truncate on table "public"."payout_audit_log" to "service_role";

grant update on table "public"."payout_audit_log" to "service_role";

grant delete on table "public"."payouts" to "anon";

grant insert on table "public"."payouts" to "anon";

grant references on table "public"."payouts" to "anon";

grant select on table "public"."payouts" to "anon";

grant trigger on table "public"."payouts" to "anon";

grant truncate on table "public"."payouts" to "anon";

grant update on table "public"."payouts" to "anon";

grant delete on table "public"."payouts" to "authenticated";

grant insert on table "public"."payouts" to "authenticated";

grant references on table "public"."payouts" to "authenticated";

grant select on table "public"."payouts" to "authenticated";

grant trigger on table "public"."payouts" to "authenticated";

grant truncate on table "public"."payouts" to "authenticated";

grant update on table "public"."payouts" to "authenticated";

grant delete on table "public"."payouts" to "service_role";

grant insert on table "public"."payouts" to "service_role";

grant references on table "public"."payouts" to "service_role";

grant select on table "public"."payouts" to "service_role";

grant trigger on table "public"."payouts" to "service_role";

grant truncate on table "public"."payouts" to "service_role";

grant update on table "public"."payouts" to "service_role";

create policy "Enable read access for all users"
on "public"."users"
as permissive
for select
to public
using (true);


CREATE TRIGGER milestone_completion_trigger AFTER UPDATE ON public.milestones FOR EACH ROW EXECUTE FUNCTION create_payout_request_on_milestone_completion();

CREATE TRIGGER milestones_set_updated_at BEFORE UPDATE ON public.milestones FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER payout_audit_trigger AFTER UPDATE ON public.payouts FOR EACH ROW EXECUTE FUNCTION log_payout_status_change();

CREATE TRIGGER payouts_set_updated_at BEFORE UPDATE ON public.payouts FOR EACH ROW EXECUTE FUNCTION set_updated_at();


