create table public.feedback (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  content text null,
  user_id uuid not null default gen_random_uuid (),
  constraint feedback_pkey primary key (id),
  constraint feedback_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;